services:
  postgres:
    image: postgres:17
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=admin
      - POSTGRES_DB=next-step
volumes:
  postgres_data:
